# Generated by Django 5.0.4 on 2024-07-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_remove_thumb_categoria_alter_thumb_plataforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumb',
            name='plataforma',
        ),
    ]
