# Generated by Django 5.0.4 on 2024-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_thumb_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='plataforma',
            field=models.CharField(choices=[('PC', 'Pc'), ('XBOX', 'Xbox'), ('PLAYSTATION', 'Playstation'), ('SWITCH', 'Switch')], max_length=50),
        ),
    ]
