# Generated by Django 5.0.4 on 2024-07-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_thumb_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumb',
            name='categoria',
            field=models.CharField(choices=[('SIMULACAO', 'Simulação'), ('ROUGUE_LIKE', 'Rougue Like'), ('SOBREVIVENCIA', 'Sobrevivência'), ('EXPLORACAO', 'Exploração')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
    ]
