# Generated by Django 5.0.4 on 2024-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_thumb_categoria_alter_thumb_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='categoria',
            field=models.CharField(choices=[('SIMULAÇÃO', 'Simulação'), ('ROUGUE_LIKE', 'Rougue Like'), ('SOBREVIVÊNCIA', 'Sobrevivência'), ('EXPLORAÇÃO', 'Exploração')], default='', max_length=100),
        ),
    ]
