# Generated by Django 5.0.4 on 2024-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_thumb_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='categoria',
            field=models.CharField(choices=[('SIMULAÇÃO', 'Simulação'), ('ROUGUELIKE', 'Rougue Like'), ('SOBREVIVÊNCIA', 'Sobrevivência'), ('EXPLORAÇÃO', 'Exploração')], default='', max_length=100),
        ),
    ]
