# Generated by Django 5.0.4 on 2024-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_alter_thumb_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='categoria',
            field=models.CharField(choices=[('SIMULACAO', 'Simulação'), ('ROUGUELIKE', 'Rougue Like'), ('SOBREVIVENCIA', 'Sobrevivência'), ('EXPLORACAO', 'Exploração')], default='', max_length=100),
        ),
    ]
