# Generated by Django 5.0.4 on 2024-08-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_alter_thumb_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumb',
            name='data_foto',
        ),
    ]
