# Generated by Django 5.0.4 on 2024-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_thumb_categoria_thumb_data_foto_thumb_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
